# 配置文件

DAILY_TIME: "14:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2021-09-29" # 纪念日
CITY: "德州"

BIRTHDAY:
  - "03-09"

APP_ID: "wx3d20fbdd30101835"
APP_SECRET: "15733797755dec41979a249273445e70"

USER_ID: 
  - "o42d_56vX_VVgEy-6d2lNMOCcEiI	"
#  - "USER ID 2" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "SVVcdTkbrwCWcw0GFegaisjJZUxSlVJtm3fJuVtpV-M"